### ISSUE TITLE
Error when entity update fails validation

### ISSUE THREAD

**Issue by weir** [crossroads/ffcrm_attachments#3]
When updating an entity that supports attachments, if the entity fails validation there is an error in the rendering of the _attachments partial. It also causes a few errors in the ffcrm unit tests in the views. The issue is that the _attachments_new template builds an entity, which of course is unsaved and has no id. Then the _attachments partial tries to render a link to it, but with a nil id it doesn't match any routes. A simple way to fix it is to add `- unless attach.new_record?` to the loop in the _attachments partial, but maybe there's a more elegant way.

**Comment by steveyken** [comment]
Thanks for this. Closing as new code now removes the build entity issue
