### ISSUE TITLE
Consider support for 'url' attachments

### ISSUE THREAD

**Issue by CloCkWeRX** [crossroads/ffcrm_attachments#6]
Not having seen this, we stuck our own document model into FFCRM recently (sigh).

Our main use case is to model Agreements (contracts) at an Organisation level, which tend to live in something like our google apps for business drive - it handles access control in a more fine grained manner.

Its pretty close to 's3 storage', just a bit more generic.

Happy to contribute to this to flesh out 'generic documents by uri' and similar (@jvnill did the heavy lifting on our side)

**Comment by steveyken** [comment]
Note: I'm pushing ActiveStorage changes to master shortly. I wonder if this should eventually get merged into FFCRM core now that ActiveStorage is a part of Rails... this plugin is really just configuration and a couple of templates (with mods for jQuery AJAX file uploads)
